### ISSUE TITLE
Coordinates are "Lat, Lon" not "Lon, Lat"

### ISSUE THREAD

**Issue by ammandul** [teeschke/intellij-geocoding-plugin#1]
"Lat, Lon" would be the correct order...

**Example**

Berlin, Mitte = 13.4023757, 52.5176896 (not really, right?)
Berlin, Mitte = 52.5176896, 13.4023757 (that would be correct)

_I'm sorry. I do not speak English very well._

**Comment by dnltsk** [comment]
Thanks for your comment! 
There is no true nor false about the order of lon and lat.
See http://www.macwright.org/lonlat/
I dicided carefully to use the lon,lat order because its the standard mathematical order of x,y or easting,northing.
In the future we could make it customizable.
Cheers and I hope that helps you out,
Daniel

**Comment by ammandul** [comment]
Thank you for the fast answer.

Mathematically, the order is correct. I agree ;).

When developing, many use the order "Lat, Lon".
An option for manually changing the order in the plugin would be awesome;).

Best regards

**Comment by dnltsk** [comment]
Hi,
lat,lon order is now customizable in the new version 1.1.0.
Give it a try and best regards,
Daniel
